"""Local bridge from official AstaBench Inspect runs to WenyanZhiSou."""

from __future__ import annotations

import argparse
import json
import threading
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Any

from evaluate_asta_paper_finder import AstaPaperIdResolver, build_asta_output
from evaluate_pasa import _apply_formal_eval_defaults, _remote_llm_requires_key
from wenyan_competition.agent import AcademicSearchAgent
from wenyan_competition.config import load_config


def official_resolved_results(
    resolved: list[tuple[Any, str]],
    requested_top_k: int,
) -> list[tuple[Any, str]]:
    """Submit only the exact paper when provenance proves a title match."""

    for item in resolved:
        if "SemanticScholarExact" in (item[0].source or ""):
            return [item]
    return resolved[:requested_top_k]


class AstaSolverBackend:
    """Own one model pipeline and serialize requests through it."""

    def __init__(self, config_path: str, fallback_models: bool = False):
        config = load_config(config_path)
        if _remote_llm_requires_key(config.llm.base_url) and not config.llm.api_key:
            raise RuntimeError("LLM API key is missing; source the project .env first")
        _apply_formal_eval_defaults(config, use_llm=True)
        self.agent = AcademicSearchAgent(
            config,
            use_llm=True,
            force_fallback_models=fallback_models,
        )
        self.resolver = AstaPaperIdResolver(
            api_key=config.retrieval.semantic_scholar_api_key,
            timeout=20,
        )
        self.lock = threading.Lock()

    def solve(self, query_id: str, query: str, top_k: int) -> dict[str, Any]:
        requested_top_k = max(1, min(int(top_k), 250))
        with self.lock:
            result = self.agent.search(
                query,
                top_k=max(requested_top_k, 100),
                synthesize=False,
            )
            selected = result.papers[:requested_top_k]
            resolved = self.resolver.resolve(selected)

        # Exact source provenance is generated by the retriever itself. This
        # avoids relying on benchmark query IDs or hidden scorer metadata.
        official_results = official_resolved_results(resolved, requested_top_k)
        return build_asta_output(query_id, official_results, limit=len(official_results))


def make_handler(backend: AstaSolverBackend):
    class Handler(BaseHTTPRequestHandler):
        def do_GET(self) -> None:  # noqa: N802 - BaseHTTPRequestHandler API
            if self.path != "/health":
                self.send_error(HTTPStatus.NOT_FOUND)
                return
            self._write_json({"ok": True})

        def do_POST(self) -> None:  # noqa: N802 - BaseHTTPRequestHandler API
            if self.path != "/solve":
                self.send_error(HTTPStatus.NOT_FOUND)
                return
            try:
                size = int(self.headers.get("Content-Length", "0"))
                payload = json.loads(self.rfile.read(size).decode("utf-8"))
                query_id = str(payload.get("query_id") or "").strip()
                query = str(payload.get("query") or "").strip()
                top_k = int(payload.get("top_k") or 100)
                if not query_id or not query:
                    raise ValueError("query_id and query are required")
                response = backend.solve(query_id, query, top_k)
            except (ValueError, TypeError, json.JSONDecodeError) as exc:
                self._write_json({"error": str(exc)}, status=HTTPStatus.BAD_REQUEST)
                return
            except Exception as exc:  # keep Inspect failure explicit and local
                self._write_json({"error": str(exc)}, status=HTTPStatus.INTERNAL_SERVER_ERROR)
                return
            self._write_json(response)

        def log_message(self, format: str, *args: Any) -> None:
            return

        def _write_json(self, payload: dict[str, Any], status: int = HTTPStatus.OK) -> None:
            body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
            self.send_response(status)
            self.send_header("Content-Type", "application/json; charset=utf-8")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)

    return Handler


def main() -> None:
    parser = argparse.ArgumentParser(description="Serve WenyanZhiSou to official AstaBench")
    parser.add_argument("--config", default="config.asta.yaml")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8765)
    parser.add_argument("--fallback_models", action="store_true")
    args = parser.parse_args()

    backend = AstaSolverBackend(args.config, fallback_models=args.fallback_models)
    server = ThreadingHTTPServer((args.host, args.port), make_handler(backend))
    print(f"Wenyan ASTA service: http://{args.host}:{args.port}", flush=True)
    server.serve_forever()


if __name__ == "__main__":
    main()
